export * from './author.service';
import { AuthorService } from './author.service';
export * from './book.service';
import { BookService } from './book.service';
export * from './bookMaterial.service';
import { BookMaterialService } from './bookMaterial.service';
export * from './category.service';
import { CategoryService } from './category.service';
export * from './material.service';
import { MaterialService } from './material.service';
export * from './office.service';
import { OfficeService } from './office.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './sale.service';
import { SaleService } from './sale.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuthorService, BookService, BookMaterialService, CategoryService, MaterialService, OfficeService, RoleService, SaleService, UserService];
