/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Book } from './book';
import { Material } from './material';


export interface BookMaterial { 
    id: number;
    amount: number;
    book: Book;
    material: Material;
    book_id: number;
    material_id: number;
}

