/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sale } from './sale';
import { Category } from './category';
import { BookMaterial } from './bookMaterial';
import { Author } from './author';


export interface Book { 
    id: number;
    name: string;
    pages: number;
    value: number;
    quantity: number;
    publishingStart: string;
    publishingEnd: string;
    sales: Array<Sale>;
    categories: Array<Category>;
    authors: Array<Author>;
    bookMaterials: Array<BookMaterial>;
}

