/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSaleDto { 
    officeId?: number;
    bookId: number;
    userId?: number;
    date: string;
    amount: number;
    price?: number;
    isExternal: boolean;
}

