/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookMaterial } from './bookMaterial';


export interface Material { 
    id: number;
    name: string;
    amount: number;
    bookMaterials: Array<BookMaterial>;
}

