/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Author } from './author';


export interface News { 
    id: number;
    title: string;
    content: string;
    publishedAt?: string;
    writer?: Author;
}

