/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sale } from './sale';
import { User } from './user';


export interface Office { 
    id: number;
    address: string;
    users: Array<User>;
    sales: Array<Sale>;
}

