/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Office } from './office';
import { User } from './user';
import { Book } from './book';


export interface Sale { 
    id: number;
    office: Office;
    book: Book;
    user: User;
    date: string;
    amount: number;
    price: number;
    isExternal: boolean;
    bookId: number;
    userId: number;
}

