/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateNewsDto { 
    title?: string;
    content?: string;
    publishedAt?: string;
    writerId?: number;
}

