/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateBookDto { 
    name?: string;
    pages?: number;
    value?: number;
    quantity?: number;
    publishingStart?: string;
    publishingEnd?: string;
    categoryIds?: Array<number>;
    authorIds?: Array<number>;
    forceQuantity?: boolean;
}

