/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Office } from './office';
import { Role } from './role';
import { Sale } from './sale';


export interface User { 
    id: number;
    name: string;
    password: string;
    email: string;
    role: Role;
    office: Office;
    sales: Array<Sale>;
}

