/**
 * Publishing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Office } from './office';
import { Role } from './role';


export interface UserData { 
    id?: number;
    name: string;
    email: string;
    role: Role;
    token?: string;
    tempPassword?: string;
    office: Office;
}

